spring:
 datasource:
  url: jdbc:mysql://flexfinder.cg0nkwgqzydh.us-east-2.rds.amazonaws.com:3306/FlexFinderDB
  username: admin 
  password: 95123578
 jpa:
  hibernate.ddl-auto: update
  generate-ddl: true
  show-sql: true
  database-platform: org.hibernate.dialect.MySQL5Dialect
