spring:
# datasource:
#  url: jdbc:mysql://172.30.42.140:3306/FlexFinderDB
#  username: admin 
#  password: 95123578
 jpa:
  hibernate.ddl-auto: update
  generate-ddl: true
  show-sql: true
  database-platform: org.hibernate.dialect.MySQL5Dialect
